# Generated by Django 2.1.1 on 2018-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('licence_no', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
