# Generated by Django 2.1.1 on 2018-11-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.CharField(max_length=100)),
                ('issu_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CarInfo')),
            ],
        ),
        migrations.RenameModel(
            old_name='Data',
            new_name='DriverInfo',
        ),
        migrations.AddField(
            model_name='tracker',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.DriverInfo'),
        ),
    ]
