# Generated by Django 2.1.1 on 2018-11-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181117_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
